---
- hosts: jenkins-vm
  become: true
  tasks:
     - name: Update App
       apt: update_cache=yes

     - name: Install Java, Wget and Git
       apt:
         pkg:
         - openjdk-8-jre
         - wget
         - git
         - curl


     - name: Allow 'jenkins' sudo access
       lineinfile:
         dest: /etc/sudoers
         state: present
         regexp: '^%jenkins'
         line: '%jenkins ALL=(ALL) NOPASSWD:ALL'
         validate: 'visudo -cf %s'

     - name: Create a login user 
       user:
         name: jenkins
         password: '???'
         state: present
         shell: /bin/bash       # Defaults to /bin/bash
         system: no             # Defaults to no
         createhome: yes        # Defaults to yes
         home: /home/jenkins  # Defaults to /home/<username>

     - name: ensure the jenkins apt repository key is installed
       apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
       become: yes

     - name: ensure the repository is configured
       apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
       become: yes

     - name: ensure jenkins is installed
       apt: name=jenkins update_cache=yes
       become: yes


     - name: Change Jenkins JAVA options
       lineinfile:
         dest=/etc/default/jenkins
         regexp=^JAVA_ARGS=
         line=JAVA_ARGS="-Djenkins.install.runSetupWizard=false"
       become: true

     - name: ensure jenkins is running
       service: name=jenkins state=started

#INSTALL DOCKER ON JENKINS VM

     - name: Install aptitude using apt
       apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

     - name: Install required system packages
       apt: name={{ item }} state=latest update_cache=yes
       loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

     - name: Add Docker GPG apt Key
       apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present

     - name: Add Docker Repository
       apt_repository:
         repo: deb https://download.docker.com/linux/ubuntu bionic stable
         state: present

     - name: Update apt and install docker-ce
       apt: update_cache=yes name=docker-ce state=latest

     - name: Add user to "docker" group
       user:
         name: "jenkins"
         group: "docker"
         append: yes

     - name: Install docker-compose
       get_url:
         url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
         dest: /usr/local/bin/docker-compose
         mode: 0755

     - name: Install Kubectl
       command: "{{ item }}"
       with_items:
         - sudo snap install kubectl --classic

     - name: Install AWS
       command: "{{ item }}"
       with_items:
         - sudo apt install awscli -y
